create table if not exists public.mandi_prices (
    id bigint generated by default as identity primary key,
    price_date date not null,
    state text not null default 'Telangana',
    district text not null default 'Nizamabad',
    mandi_name text not null,
    mandi_slug text not null,
    crop_name text not null,
    crop_slug text not null,
    variety text not null default 'unknown',
    min_price_rs_per_qtl integer,
    max_price_rs_per_qtl integer,
    modal_price_rs_per_qtl integer,
    source text not null,
    source_resource text,
    fetched_at_utc timestamptz not null default timezone('utc', now()),
    raw_record jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists mandi_prices_unique_row_idx
on public.mandi_prices (
    price_date,
    mandi_slug,
    crop_slug,
    source,
    variety
);

create index if not exists mandi_prices_date_idx
on public.mandi_prices (price_date desc);

create index if not exists mandi_prices_lookup_idx
on public.mandi_prices (mandi_slug, crop_slug, price_date desc);
