create table if not exists public.weather_hourly_forecasts (
    id bigint generated by default as identity primary key,
    location_name text not null default 'Nizamabad',
    location_slug text not null default 'nizamabad',
    forecast_time timestamptz not null,
    latitude double precision not null,
    longitude double precision not null,
    timezone text not null default 'Asia/Kolkata',
    precipitation_probability_pct integer,
    temperature_2m_c double precision,
    relative_humidity_2m_pct integer,
    cloud_cover_pct integer,
    rain_mm double precision,
    showers_mm double precision,
    weather_code integer,
    source text not null default 'open_meteo',
    fetched_at_utc timestamptz not null default timezone('utc', now()),
    raw_record jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists weather_hourly_forecasts_unique_idx
on public.weather_hourly_forecasts (forecast_time, location_slug, source);

create index if not exists weather_hourly_forecasts_lookup_idx
on public.weather_hourly_forecasts (location_slug, forecast_time desc);

create table if not exists public.weather_daily_forecasts (
    id bigint generated by default as identity primary key,
    location_name text not null default 'Nizamabad',
    location_slug text not null default 'nizamabad',
    forecast_date date not null,
    latitude double precision not null,
    longitude double precision not null,
    timezone text not null default 'Asia/Kolkata',
    temperature_2m_max_c double precision,
    temperature_2m_min_c double precision,
    precipitation_probability_max_pct integer,
    precipitation_sum_mm double precision,
    weather_code integer,
    source text not null default 'open_meteo',
    fetched_at_utc timestamptz not null default timezone('utc', now()),
    raw_record jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists weather_daily_forecasts_unique_idx
on public.weather_daily_forecasts (forecast_date, location_slug, source);

create index if not exists weather_daily_forecasts_lookup_idx
on public.weather_daily_forecasts (location_slug, forecast_date desc);
