create table if not exists public.recommendation_log (
    id bigint generated by default as identity primary key,
    season text not null,
    farmer_key text not null,
    farmer_id text,
    survey_number text,
    mandal text not null,
    soil_zone text not null,
    water_source text not null,
    acres double precision not null default 0,
    primary_crop text not null,
    secondary_crop text,
    source text not null default 'engine',
    logged_at_utc timestamptz not null default timezone('utc', now())
);

create unique index if not exists recommendation_log_season_farmer_key_uidx
on public.recommendation_log (season, farmer_key);

create index if not exists recommendation_log_season_idx
on public.recommendation_log (season);

create index if not exists recommendation_log_primary_crop_idx
on public.recommendation_log (primary_crop);
