create table if not exists public.farmer_profiles (
    id bigint generated by default as identity primary key,
    phone_number text not null unique,
    mandal text,
    acres double precision,
    soil_type text,
    water_source text,
    last_three_crops jsonb not null default '[]'::jsonb,
    loan_situation text,
    loan_burden_rs integer not null default 0,
    profile_stage text not null default 'mandal',
    profile_complete boolean not null default false,
    created_at_utc timestamptz not null default timezone('utc', now()),
    updated_at_utc timestamptz not null default timezone('utc', now())
);

create index if not exists farmer_profiles_mandal_idx
on public.farmer_profiles (mandal);
